# Generated by Django 3.2.25 on 2024-03-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.s3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('default', 'Default'), ('premium', 'Premium')], default='default', max_length=16)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('user', 'profile-picture'))),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('max_streak', models.IntegerField(null=True)),
                ('app_version', models.CharField(default='EN', max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=265)),
                ('message', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(blank=True, choices=[('default', 'Default'), ('confirm', 'Confirm')], max_length=20, null=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
