# Generated by Django 3.2.25 on 2024-03-31 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_badge', to='streaks.badge'),
        ),
        migrations.AddField(
            model_name='notification',
            name='streak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_streak', to='streaks.streak'),
        ),
    ]
