# Generated by Django 3.2.25 on 2024-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240331_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_language',
            field=models.CharField(default='EN', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='app_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
