# Generated by Django 3.2.25 on 2024-03-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.s3
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rarity_order', models.IntegerField()),
                ('name', models.TextField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=265)),
                ('duration_in_seconds', models.IntegerField()),
                ('description', models.TextField(max_length=1024)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreakCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_category', to='streaks.streakcategory')),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_streak', to='streaks.streak')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreakTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_in_seconds', models.IntegerField()),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=1024)),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_user_streak', to='streaks.userstreak')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=265)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('badge', 'badge-icon'))),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_rarity', to='streaks.badgerarity')),
            ],
        ),
    ]
