# Generated by Django 3.2.25 on 2024-04-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='duration_in_seconds',
            new_name='duration_days',
        ),
        migrations.RenameField(
            model_name='streaktrack',
            old_name='duration_in_seconds',
            new_name='duration_days',
        ),
    ]
