# Generated by Django 3.2.25 on 2024-04-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0003_rename_duration_days_streaktrack_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaktrack',
            old_name='streak',
            new_name='user_streak',
        ),
    ]
