# Generated by Django 3.2.25 on 2024-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0004_rename_streak_streaktrack_user_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaktrack',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
