# Generated by Django 3.2.25 on 2024-04-07 13:03

from django.db import migrations, models
import helpers.s3
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0005_alter_streaktrack_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('streak', 'streak-background')),
        ),
        migrations.AddField(
            model_name='userstreak',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
