# Generated by Django 3.2.25 on 2024-04-07 13:20

from django.db import migrations, models
import helpers.s3


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0006_auto_20240407_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstreak',
            name='background_picture',
        ),
        migrations.AddField(
            model_name='streak',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.s3.UploadFileTo('streak', 'streak-background')),
        ),
    ]
