# Generated by Django 3.2.25 on 2024-04-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0007_auto_20240407_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstreak',
            name='status',
            field=models.CharField(choices=[('day_done', 'Day Gone'), ('pending', 'Pending'), ('streak_over', 'Streak Over')], default='pending', max_length=16),
        ),
    ]
