# Generated by Django 3.2.25 on 2024-04-11 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0008_userstreak_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='streak',
            name='min_time_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
