# Generated by Django 3.2.25 on 2024-04-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0009_auto_20240411_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
    ]
