# Generated by Django 3.2.25 on 2024-08-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0012_auto_20240825_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaktrack',
            old_name='duration',
            new_name='minutes',
        ),
        migrations.RemoveField(
            model_name='streaktrack',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='streaktrack',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='streaktrack',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
